%YAML:1.0

# image　and imu settings 
img_frame_rate: 50
imu_frame_rate: 200
auto_exposure: 1
exposure_time: 3
gain: 3

# imu低通滤波,目前只支持(0,1)这一档
#flag    0    1    2    3     4     5     6 
#acc(ms) 1.94 5.80 7.80 11.80 19.80 35.70 66.96
#gyr(ms) 0.97 2.9  3.9  5.9   9.9   17.85 33.48 
#
dlfp_acc: 0 
dlfp_gyr: 1

#时间差补偿

# imu标定方法：先算温漂，再用imu_tk算bias、scale和轴间误差
# 注意：这里没有处理逐次开机噪声
# 温漂只考虑到30～55°之间的，其它暂时没有测试
# imu settings
temperature_compensation: 1
bias_correction: 1
scale_correction: 1
axis_alignment: 1

#temperature compensation
tempdriftscale_acc: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 0.2008, 0.5773, -0.4664 ]

tempdriftscale_gyr: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -0.3423, -0.2595, 0.04857 ]

# bias correction
bias_acc: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 30.1681, 54.5531, -49.5212 ]

bias_gyr: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -9.82607, -6.24055, 10.2871 ]


# scale correction
Ka:!!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.00239087,  0,          0,
           0,           0.00238991, 0,
           0,           0,          0.00238597 ]

Kg:!!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.00107003,          0,          0,
           0,          0.00106816,          0,
           0,                   0, 0.00106858 ]

# axis alignment
Ta:!!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1,  -0.000681055,  0.0012025,
           0,            1, -0.00544407,
          -0,            0,            1 ]

Tg:!!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1,          -0.00026484, 0.00387326,
          -0.000795577,          1,-0.000209565,
           0.000290412, -0.0065115,           1 ]
          
#time shift camera to imu
tsc2i: !!opencv-matrix
   rows: 2
   cols: 3
   dt: d
   data: [ 200       ,  500,        1000,
          1350       ,    0,           0           ]
