%YAML:1.0

# image　and imu settings 
img_frame_rate: 20
imu_frame_rate: 200
auto_exposure: 1
exposure_time: 3
gain: 3

# imu标定方法：先算温漂，再用imu_tk算bias、scale和轴间误差
# 注意：这里没有处理逐次开机噪声
# 温漂只考虑到30～55°之间的，其它暂时没有测试
# imu settings
temperature_compensation: 1
bias_correction: 1
scale_correction: 1
axis_alignment: 1

#temperature compensation
tempdriftscale_acc: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -2.02, 2.719, -4.063 ]

tempdriftscale_gyr: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 0.2963, -0.3643, -0.09578 ]

# bias correction
bias_acc: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -49.0992, 85.5568,-155.375]

bias_gyr: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -33.6926,-2.06408, 8.51697]


# scale correction
Ka:!!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.00239378,  0,          0,
           0,           0.00238906, 0,
           0,           0,          0.00238113 ]

Kg:!!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.00107028,          0,          0,
           0,           0.00106483,          0,
           0,                   0, 0.00106717 ]

# axis alignment
Ta:!!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1,  0.00154246, 0.0033918,
           0,            1, 0.0016961,
          -0,            0,            1 ]

Tg:!!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1,           8.1987e-05,  0.00620922,
          -0.00201329,            1, 0.00134609,
          0.0035647,  -0.00154674,            1 ]
