%YAML:1.0

# image　and imu settings 
img_frame_rate: 30
imu_frame_rate: 200
auto_exposure: 1
exposure_time: 3
gain: 3

# imu标定方法：先算温漂，再用imu_tk算bias、scale和轴间误差
# 注意：这里没有处理逐次开机噪声
# 温漂只考虑到30～55°之间的，其它暂时没有测试
# imu settings
temperature_compensation: 0
bias_correction: 0
scale_correction: 0
axis_alignment: 0

#temperature compensation
tempdriftscale_acc: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -2.183, 2.59, -3.159 ]

tempdriftscale_gyr: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 0.01107, -0.48, -0.07808 ]

# bias correction
bias_acc: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -61.4186, 80.5942, 59.8464 ]

bias_gyr: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -44.2969, 2.96049, 9.93558 ]


# scale correction
Ka:!!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.00239566,  0,          0,
           0,           0.00239213, 0,
           0,           0,          0.00238436 ]

Kg:!!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.00107145,          0,          0,
           0,           0.0010622,          0,
           0,                   0, 0.00106697 ]

# axis alignment
Ta:!!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1,  0.000126062,   0.00433082,
           0,            1, -0.000588582,
          -0,            0,            1 ]

Tg:!!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1,           -0.00040889,  0.00597846,
          -2.5504e-05,            1, 0.000856756,
          0.00452604,  -0.000504418,            1 ]
