%YAML:1.0

# image　and imu settings 
img_frame_rate: 20
imu_frame_rate: 200
auto_exposure: 1
exposure_time: 3
gain: 3

# imu低通滤波,目前只支持(0,1)这一档
#flag    0    1    2    3     4     5     6 
#acc(ms) 1.94 5.80 7.80 11.80 19.80 35.70 66.96
#gyr(ms) 0.97 2.9  3.9  5.9   9.9   17.85 33.48 
#
dlfp_acc: 4 # 0
dlfp_gyr: 5 # 1 

#时间差补偿

# imu标定方法：先算温漂，再用imu_tk算bias、scale和轴间误差
# 注意：这里没有处理逐次开机噪声
# 温漂只考虑到30～55°之间的，其它暂时没有测试
# imu settings
temperature_compensation: 1
bias_correction: 1
scale_correction: 1
axis_alignment: 1

#temperature compensation
tempdriftscale_acc: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 0.2008, 0.5773, -0.4664 ]

tempdriftscale_gyr: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -0.3423, -0.2595, 0.04857 ]

# bias correction
bias_acc: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 39.4565, 42.1746, -23.0405 ]

bias_gyr: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -3.91817, -2.59884, 14.1206 ]


# scale correction
Ka:!!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.00239159,          0,          0,
           0, 0.00239062,          0,
           0,          0, 0.00238457]

Kg:!!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.00107212,          0,          0,
         0, 0.00106848,          0,
         0,          0,  0.0010688]

# axis alignment
Ta:!!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [   1, 5.30936e-05,  0.00173492,
             0,           1, -0.00613538,
            -0,           0,           1]

Tg:!!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1,  0.000445165,  0.000220397,
          0.000175782,            1,  0.000496626,
         -0.000678526,  -0.00687171,            1]
          
#time shift camera to imu,us
tsc2i: !!opencv-matrix
   rows: 2
   cols: 3
   dt: d
   data: [ 200       ,  500,        1000,
          0       ,    0,           0           ]
