%YAML:1.0

# image　and imu settings 
img_frame_rate: 20
imu_frame_rate: 200
auto_exposure: 1
exposure_time: 3
gain: 3

# imu低通滤波,目前只支持(0,1)这一档
#flag    0    1    2    3     4     5     6 
#acc(ms) 1.94 5.80 7.80 11.80 19.80 35.70 66.96
#gyr(ms) 0.97 2.9  3.9  5.9   9.9   17.85 33.48 
#
dlfp_acc: 0 
dlfp_gyr: 1

#时间差补偿

# imu标定方法：先算温漂，再用imu_tk算bias、scale和轴间误差
# 注意：这里没有处理逐次开机噪声
# 温漂只考虑到30～55°之间的，其它暂时没有测试
# imu settings
temperature_compensation: 1
bias_correction: 1
scale_correction: 1
axis_alignment: 1

#temperature compensation
tempdriftscale_acc: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 0.2223, 0.1973, -3.646 ]

tempdriftscale_gyr: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -0.01617, -0.3227, 0.1227 ]

# bias correction
bias_acc: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 41.8964, 65.9615, -327.422 ]

bias_gyr: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 0.6079, -11.8128, 7.9401 ]


# scale correction
Ka:!!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.00239323,  0,          0,
           0,           0.00239893, 0,
           0,           0,          0.00236974 ]

Kg:!!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.00107107,          0,          0,
           0,          0.00106469,          0,
           0,                   0, 0.00106611 ]

# axis alignment
Ta:!!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1,  0.000231275,  0.00278233,
           0,            1,  0.000232769,
          -0,            0,            1 ]

Tg:!!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1,          -0.00026484, 0.00387326,
          0.000238425,           1, 0.00161024,
         -0.000273122,  -0.0015077,           1 ]
          
#time shift camera to imu
tsc2i: !!opencv-matrix
   rows: 2
   cols: 3
   dt: d
   data: [ 200       ,  500,        1000,
          1350       ,    0,           0           ]
