%YAML:1.0

# image　and imu settings 
# supported image frame rate: 20hz, 25hz, 30hz 50hz
# supported imu frame rate: 200hz, 500hz, 1000hz
img_frame_rate: 20
imu_frame_rate: 200
auto_exposure: 1
exposure_time: 3
gain: 3

# imu低通滤波,目前只支持(0,1)这一档
#flag    0    1    2    3     4     5     6 
#acc(ms) 1.94 5.80 7.80 11.80 19.80 35.70 66.96
#gyr(ms) 0.97 2.9  3.9  5.9   9.9   17.85 33.48 
#
dlfp_acc: 0 
dlfp_gyr: 1

#时间差补偿

# imu标定方法：先算温漂，再用imu_tk算bias、scale和轴间误差
# 注意：这里没有处理逐次开机噪声
# 温漂只考虑到30～55°之间的，其它暂时没有测试
# imu settings
temperature_compensation: 1
bias_correction: 1
scale_correction: 1
axis_alignment: 1

#temperature compensation
tempdriftscale_acc: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-1.495, -1.056, -2.739 ]

tempdriftscale_gyr: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 0.09668, 0.1178, 0.05815]

# bias correction
bias_acc: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -63, 6, -113]

bias_gyr: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 20, -5, -7 ]


# scale correction
Ka: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.00239494,  0,          0,
           0,           0.00239049, 0,
           0,           0,          0.00237146 ]

Kg: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.00107457,          0,          0,
           0,          0.00106731,          0,
           0,                   0, 0.00105403 ]

# axis alignment
Ta: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1,    0.000814469, 0.00514832,
           0,            1,  0.000348817,
          -0,            0,            1 ]

Tg: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1,  0.00862461,  0.00893992,
           -0.00786815, 1,  0.00346665,
           0.0045402,  0.00655649,   1 ]
          
#time shift camera to imu
tsc2i: !!opencv-matrix
   rows: 2
   cols: 3
   dt: d
   data: [ 200       ,  500,        1000,
          1400       ,  150,        -250           ]

